# Tag list for GUI selector - matches COLOR_KEYS in overlay.py
TAG_LIST = [
    "glyph_boxes",
    "rows",
    "regular_blocks",
    "table_blocks",
    "header_blocks",
    "notes_columns",
    "legend_region",
    "legend_header",
    "abbreviation_region",
    "abbreviation_header",
    "abbreviation_code",
    "abbreviation_meaning",
    "abbreviation_line",
    "revision_region",
    "revision_header",
    "revision_entry",
    "misc_title_region",
    "misc_title_text",
    "standard_detail_region",
    "standard_detail_header",
    "standard_detail_subheader",
    "standard_detail_sheet",
    "standard_detail_description",
]

TAG_DESCRIPTIONS = {
    "glyph_boxes": "Individual word boxes",
    "rows": "Horizontal row of glyph boxes",
    "regular_blocks": "Cluster of rows (paragraph/table)",
    "table_blocks": "Block detected as a table",
    "header_blocks": "Block is a header",
    "notes_columns": "Header + associated notes blocks",
    "legend_region": "Legend outer region box",
    "legend_header": "Legend header",
    "abbreviation_region": "Abbreviation outer region box",
    "abbreviation_header": "Abbreviation header",
    "abbreviation_code": "Code in abbreviation entry",
    "abbreviation_meaning": "Meaning in abbreviation entry",
    "abbreviation_line": "Connecting line in abbreviation entry",
    "revision_region": "Revision outer region box",
    "revision_header": "Revision header",
    "revision_entry": "Revision entry row",
    "misc_title_region": "Miscellaneous title box",
    "misc_title_text": "Combined text in misc title box",
    "standard_detail_region": "Standard details outer box",
    "standard_detail_header": "Standard details header",
    "standard_detail_subheader": "Standard details subheader",
    "standard_detail_sheet": "Sheet number in standard details",
    "standard_detail_description": "Description in standard details",
}
